Add IgnoreArch config option to [build]
actionless/pikaur pull request #566
Opened 2021-05-12 20:40 UTC by cryzed

This adds an option `IgnoreArch` to the `[build]`-section of the configuration file, which defaults to `no`. When set to `yes`, all warnings and prompts regarding architecture mismatches between the host system and the `arch`-array in the PKGBUILD will be skipped and `--ignorearch` will be passed to `makepkg` when building the package.

I started patching this before I noticed that the "error" about an architecture mismatch is really more of a warning prompt, and `--noconfirm` will accept the prompt and simply continue -- I originally expected this to abort the sync process or skip updating the package. As it stands, this setting isn't strictly _necessary_ for my own use after this discovery, but I thought maybe still useful enough to be merged.

2021-05-12 22:38 UTC, actionless requested changes
also in ` def build_with_makepkg()` you need to add the flag for makepkg

2021-05-12 22:56 UTC, cryzed commented
The flag should be added already: I initialize `skip_carch_check` in `PackageBuild`'s constructor with the value from the config. Later in `build_with_makepkg()` we will enter the `if self.skip_carch_check`-branch, which will add `--ignorearch` to makepkg's arguments. Am I misunderstanding?

2021-05-13 00:58 UTC, actionless commented
oh, i forgot what it's already implemented for another issue

2021-05-13 01:32 UTC, cryzed commented
I don't quite follow -- do you still need me to change something?

2021-05-13 11:41 UTC, merged

2021-05-13 11:41 UTC, actionless commented
nope, thanks for the contribution!